name: el primer deploy iac
on: workflow_dispatch
env:
  AZURERG: thorappdemo_group
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Bicep
        uses: anthony-c-martin/setup-bicep@v0.1

      - name: Build Bicep
        run: bicep build ./main.bicep

      
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Bicep
        uses: anthony-c-martin/setup-bicep@v0.1

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Bicep
        # path to your checked-in .bicep file to deploy
        run: bicep build ./main.bicep

      - name: deploy
      - uses: azure/arm-deploy@v1
        with:
          # set to your subscriptionId si todo está bien
          subscriptionId: f5d717f3-a0e8-40ea-b6ba-8bbfb3174294
#          # set to your resource group name
          resourceGroupName: ${{env.AZURERG}}
  #        # should match the .bicep file path but with .json extension
          template: ./main.bicep
#          # path to your checked-in parameters file to deploy
 #         parameters: ./path/to/parameters.json
          failOnStdErr: false
        
